logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/case_db?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.itgq.domain



